// <auto-generated />
using System;
using AirlineCompany.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirlineCompany.Domain.Migrations
{
    [DbContext(typeof(AirlineCompanyDbContext))]
    [Migration("20241202160853_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AirlineCompany.Domain.Models.AirFlight", b =>
                {
                    b.Property<int>("Idflight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_flight");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Idflight"));

                    b.Property<string>("ArrivalPoint")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("arrival_point");

                    b.Property<DateTime>("Arrive")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("arrive");

                    b.Property<string>("CodeNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("code_number");

                    b.Property<DateTime>("Departure")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("departure");

                    b.Property<string>("DeparturePoint")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("departure_point");

                    b.Property<TimeOnly>("FlyingTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("flying_time");

                    b.Property<int>("PlaneId")
                        .HasColumnType("int")
                        .HasColumnName("id_plane");

                    b.HasKey("Idflight");

                    b.HasIndex("PlaneId");

                    b.ToTable("airflights");

                    b.HasData(
                        new
                        {
                            Idflight = 1,
                            ArrivalPoint = "Dublin",
                            Arrive = new DateTime(2024, 3, 23, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            CodeNumber = "1000",
                            Departure = new DateTime(2024, 3, 23, 16, 39, 0, 0, DateTimeKind.Unspecified),
                            DeparturePoint = "Tokio",
                            FlyingTime = new TimeOnly(4, 21, 0),
                            PlaneId = 1
                        },
                        new
                        {
                            Idflight = 2,
                            ArrivalPoint = "Amsterdam",
                            Arrive = new DateTime(2024, 9, 2, 1, 39, 0, 0, DateTimeKind.Unspecified),
                            CodeNumber = "2000",
                            Departure = new DateTime(2024, 9, 1, 16, 35, 0, 0, DateTimeKind.Unspecified),
                            DeparturePoint = "Rome",
                            FlyingTime = new TimeOnly(9, 4, 0),
                            PlaneId = 4
                        },
                        new
                        {
                            Idflight = 3,
                            ArrivalPoint = "Vienna",
                            Arrive = new DateTime(2024, 11, 24, 12, 1, 0, 0, DateTimeKind.Unspecified),
                            CodeNumber = "3000",
                            Departure = new DateTime(2024, 11, 23, 23, 50, 0, 0, DateTimeKind.Unspecified),
                            DeparturePoint = "Rome",
                            FlyingTime = new TimeOnly(12, 11, 0),
                            PlaneId = 4
                        },
                        new
                        {
                            Idflight = 4,
                            ArrivalPoint = "St. Petersburg",
                            Arrive = new DateTime(2024, 6, 26, 22, 39, 0, 0, DateTimeKind.Unspecified),
                            CodeNumber = "4000",
                            Departure = new DateTime(2024, 6, 26, 17, 17, 0, 0, DateTimeKind.Unspecified),
                            DeparturePoint = "London",
                            FlyingTime = new TimeOnly(5, 22, 0),
                            PlaneId = 5
                        },
                        new
                        {
                            Idflight = 5,
                            ArrivalPoint = "Amsterdam",
                            Arrive = new DateTime(2024, 9, 26, 2, 21, 0, 0, DateTimeKind.Unspecified),
                            CodeNumber = "5000",
                            Departure = new DateTime(2024, 9, 25, 23, 1, 0, 0, DateTimeKind.Unspecified),
                            DeparturePoint = "Moscow",
                            FlyingTime = new TimeOnly(3, 20, 0),
                            PlaneId = 3
                        },
                        new
                        {
                            Idflight = 6,
                            ArrivalPoint = "Dublin",
                            Arrive = new DateTime(2024, 12, 19, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            CodeNumber = "6000",
                            Departure = new DateTime(2024, 12, 19, 4, 20, 0, 0, DateTimeKind.Unspecified),
                            DeparturePoint = "Samara",
                            FlyingTime = new TimeOnly(10, 10, 0),
                            PlaneId = 4
                        },
                        new
                        {
                            Idflight = 7,
                            ArrivalPoint = "Dublin",
                            Arrive = new DateTime(2024, 1, 29, 3, 46, 0, 0, DateTimeKind.Unspecified),
                            CodeNumber = "7000",
                            Departure = new DateTime(2024, 1, 28, 19, 20, 0, 0, DateTimeKind.Unspecified),
                            DeparturePoint = "Rome",
                            FlyingTime = new TimeOnly(8, 26, 0),
                            PlaneId = 1
                        },
                        new
                        {
                            Idflight = 8,
                            ArrivalPoint = "Washington",
                            Arrive = new DateTime(2024, 6, 3, 19, 11, 0, 0, DateTimeKind.Unspecified),
                            CodeNumber = "8000",
                            Departure = new DateTime(2024, 6, 3, 15, 43, 0, 0, DateTimeKind.Unspecified),
                            DeparturePoint = "Tokio",
                            FlyingTime = new TimeOnly(3, 28, 0),
                            PlaneId = 4
                        },
                        new
                        {
                            Idflight = 9,
                            ArrivalPoint = "Vienna",
                            Arrive = new DateTime(2024, 7, 14, 0, 20, 0, 0, DateTimeKind.Unspecified),
                            CodeNumber = "9000",
                            Departure = new DateTime(2024, 7, 13, 12, 23, 0, 0, DateTimeKind.Unspecified),
                            DeparturePoint = "Moscow",
                            FlyingTime = new TimeOnly(11, 57, 0),
                            PlaneId = 3
                        });
                });

            modelBuilder.Entity("AirlineCompany.Domain.Models.Passeneger", b =>
                {
                    b.Property<int>("IdPassenger")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_passenger");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPassenger"));

                    b.Property<double>("BaggageWeight")
                        .HasColumnType("double")
                        .HasColumnName("baggage_weight");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("fullname");

                    b.Property<int>("IdFlight")
                        .HasColumnType("int")
                        .HasColumnName("id_flight");

                    b.Property<string>("Passport")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("passport");

                    b.Property<bool>("Registration")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("registration");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("seat_number");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ticket_number");

                    b.HasKey("IdPassenger");

                    b.ToTable("passengers");

                    b.HasData(
                        new
                        {
                            IdPassenger = 1,
                            BaggageWeight = 0.0,
                            FullName = "Belyackova Veronicka Sergeevna",
                            IdFlight = 4,
                            Passport = "3678678903",
                            Registration = true,
                            SeatNumber = "A18",
                            TicketNumber = "35999"
                        },
                        new
                        {
                            IdPassenger = 2,
                            BaggageWeight = 8.5999999999999996,
                            FullName = "Nenashev Ivan Nickolayevich",
                            IdFlight = 0,
                            Passport = "5678359284",
                            Registration = true,
                            SeatNumber = "E6",
                            TicketNumber = "78112"
                        },
                        new
                        {
                            IdPassenger = 3,
                            BaggageWeight = 2.7000000000000002,
                            FullName = "Zamotohina Maria Andreevna",
                            IdFlight = 4,
                            Passport = "2875909090",
                            Registration = true,
                            SeatNumber = "E7",
                            TicketNumber = "97966"
                        },
                        new
                        {
                            IdPassenger = 4,
                            BaggageWeight = 7.5,
                            FullName = "Chumackov Michail Vladimirovich",
                            IdFlight = 0,
                            Passport = "837968585",
                            Registration = true,
                            SeatNumber = "D15",
                            TicketNumber = "80318"
                        },
                        new
                        {
                            IdPassenger = 5,
                            BaggageWeight = 8.8000000000000007,
                            FullName = "Zhuckov Semyon Viktorovich",
                            IdFlight = 5,
                            Passport = "7492748492",
                            Registration = true,
                            SeatNumber = "E8",
                            TicketNumber = "46692"
                        },
                        new
                        {
                            IdPassenger = 6,
                            BaggageWeight = 9.5,
                            FullName = "Chumackov Michail Vladimirovich",
                            IdFlight = 3,
                            Passport = "837968585",
                            Registration = true,
                            SeatNumber = "F5",
                            TicketNumber = "12681"
                        },
                        new
                        {
                            IdPassenger = 7,
                            BaggageWeight = 7.0,
                            FullName = "Zamotohina Maria Andreevna",
                            IdFlight = 0,
                            Passport = "2875909090",
                            Registration = true,
                            SeatNumber = "A13",
                            TicketNumber = "18614"
                        },
                        new
                        {
                            IdPassenger = 8,
                            BaggageWeight = 6.5999999999999996,
                            FullName = "Belyackova Veronicka Sergeevna",
                            IdFlight = 6,
                            Passport = "3678678903",
                            Registration = true,
                            SeatNumber = "E11",
                            TicketNumber = "52424"
                        },
                        new
                        {
                            IdPassenger = 9,
                            BaggageWeight = 0.0,
                            FullName = "Nenashev Ivan Nickolayevich",
                            IdFlight = 4,
                            Passport = "5678359284",
                            Registration = true,
                            SeatNumber = "D13",
                            TicketNumber = "71384"
                        },
                        new
                        {
                            IdPassenger = 10,
                            BaggageWeight = 4.0,
                            FullName = "Nenashev Ivan Nickolayevich",
                            IdFlight = 6,
                            Passport = "5678359284",
                            Registration = true,
                            SeatNumber = "E16",
                            TicketNumber = "57713"
                        },
                        new
                        {
                            IdPassenger = 11,
                            BaggageWeight = 2.2999999999999998,
                            FullName = "Belyackova Veronicka Sergeevna",
                            IdFlight = 8,
                            Passport = "3678678903",
                            Registration = true,
                            SeatNumber = "A8",
                            TicketNumber = "76112"
                        },
                        new
                        {
                            IdPassenger = 12,
                            BaggageWeight = 7.2000000000000002,
                            FullName = "Nenashev Ivan Nickolayevich",
                            IdFlight = 5,
                            Passport = "5678359284",
                            Registration = true,
                            SeatNumber = "C16",
                            TicketNumber = "31952"
                        },
                        new
                        {
                            IdPassenger = 13,
                            BaggageWeight = 8.4000000000000004,
                            FullName = "Zemlyanov Vladimir Borisovich",
                            IdFlight = 6,
                            Passport = "1234567890",
                            Registration = true,
                            SeatNumber = "A13",
                            TicketNumber = "30020"
                        },
                        new
                        {
                            IdPassenger = 14,
                            BaggageWeight = 1.3,
                            FullName = "Belyackova Veronicka Sergeevna",
                            IdFlight = 2,
                            Passport = "3678678903",
                            Registration = true,
                            SeatNumber = "E17",
                            TicketNumber = "15824"
                        },
                        new
                        {
                            IdPassenger = 15,
                            BaggageWeight = 2.2000000000000002,
                            FullName = "Zemlyanov Vladimir Borisovich",
                            IdFlight = 7,
                            Passport = "1234567890",
                            Registration = true,
                            SeatNumber = "C17",
                            TicketNumber = "96981"
                        },
                        new
                        {
                            IdPassenger = 16,
                            BaggageWeight = 8.0999999999999996,
                            FullName = "Zemlyanov Vladimir Borisovich",
                            IdFlight = 1,
                            Passport = "1234567890",
                            Registration = true,
                            SeatNumber = "D8",
                            TicketNumber = "36824"
                        },
                        new
                        {
                            IdPassenger = 17,
                            BaggageWeight = 7.2999999999999998,
                            FullName = "Zemlyanov Vladimir Borisovich",
                            IdFlight = 8,
                            Passport = "1234567890",
                            Registration = true,
                            SeatNumber = "C6",
                            TicketNumber = "45619"
                        },
                        new
                        {
                            IdPassenger = 18,
                            BaggageWeight = 5.7999999999999998,
                            FullName = "Nenashev Ivan Nickolayevich",
                            IdFlight = 2,
                            Passport = "5678359284",
                            Registration = true,
                            SeatNumber = "A14",
                            TicketNumber = "44659"
                        },
                        new
                        {
                            IdPassenger = 19,
                            BaggageWeight = 7.0,
                            FullName = "Zemlyanov Vladimir Borisovich",
                            IdFlight = 2,
                            Passport = "1234567890",
                            Registration = true,
                            SeatNumber = "C17",
                            TicketNumber = "58068"
                        },
                        new
                        {
                            IdPassenger = 20,
                            BaggageWeight = 3.1000000000000001,
                            FullName = "Zamotohina Maria Andreevna",
                            IdFlight = 8,
                            Passport = "2875909090",
                            Registration = true,
                            SeatNumber = "C12",
                            TicketNumber = "67255"
                        });
                });

            modelBuilder.Entity("AirlineCompany.Domain.Models.Plane", b =>
                {
                    b.Property<int>("IdPlane")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_plane");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPlane"));

                    b.Property<double>("Efficiency")
                        .HasColumnType("double")
                        .HasColumnName("efficiency");

                    b.Property<double>("LoadCapacity")
                        .HasColumnType("double")
                        .HasColumnName("load_capacity");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("model");

                    b.Property<int>("PassengerMax")
                        .HasColumnType("int")
                        .HasColumnName("passenger_max");

                    b.HasKey("IdPlane");

                    b.ToTable("planes");

                    b.HasData(
                        new
                        {
                            IdPlane = 1,
                            Efficiency = 334.0,
                            LoadCapacity = 4.0,
                            Model = "NG Model 15001",
                            PassengerMax = 210
                        },
                        new
                        {
                            IdPlane = 2,
                            Efficiency = 367.0,
                            LoadCapacity = 4.5,
                            Model = "NG Model 20103",
                            PassengerMax = 210
                        },
                        new
                        {
                            IdPlane = 3,
                            Efficiency = 334.0,
                            LoadCapacity = 3.5,
                            Model = "Panda 202015",
                            PassengerMax = 165
                        },
                        new
                        {
                            IdPlane = 4,
                            Efficiency = 949.0,
                            LoadCapacity = 12.0,
                            Model = "Panda 202208",
                            PassengerMax = 210
                        },
                        new
                        {
                            IdPlane = 5,
                            Efficiency = 949.0,
                            LoadCapacity = 2.7000000000000002,
                            Model = "NG Model 22009",
                            PassengerMax = 170
                        },
                        new
                        {
                            IdPlane = 6,
                            Efficiency = 329.0,
                            LoadCapacity = 2.7000000000000002,
                            Model = "Herpa 515726",
                            PassengerMax = 165
                        });
                });

            modelBuilder.Entity("AirlineCompany.Domain.Models.AirFlight", b =>
                {
                    b.HasOne("AirlineCompany.Domain.Models.Plane", "Plane")
                        .WithMany()
                        .HasForeignKey("PlaneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plane");
                });
#pragma warning restore 612, 618
        }
    }
}
