// <auto-generated />
using System;
using AirlineCompany.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirlineCompany.Domain.Migrations
{
    [DbContext(typeof(AirlineCompanyDbContext))]
    partial class AirlineCompanyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AirlineCompany.Domain.Models.AirFlight", b =>
                {
                    b.Property<int>("Idflight")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_flight");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Idflight"));

                    b.Property<string>("ArrivalPoint")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("arrival_point");

                    b.Property<DateTime>("Arrive")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("arrive");

                    b.Property<string>("CodeNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("code_number");

                    b.Property<DateTime>("Departure")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("departure");

                    b.Property<string>("DeparturePoint")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("departure_point");

                    b.Property<TimeOnly>("FlyingTime")
                        .HasColumnType("time(6)")
                        .HasColumnName("flying_time");

                    b.Property<int>("id_plane")
                        .HasColumnType("int");

                    b.HasKey("Idflight");

                    b.HasIndex("id_plane");

                    b.ToTable("airflights");
                });

            modelBuilder.Entity("AirlineCompany.Domain.Models.Passeneger", b =>
                {
                    b.Property<int>("IdPassenger")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_passenger");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPassenger"));

                    b.Property<double>("BaggageWeight")
                        .HasColumnType("double")
                        .HasColumnName("baggage_weight");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("fullname");

                    b.Property<int>("IdFlight")
                        .HasColumnType("int")
                        .HasColumnName("id_flight");

                    b.Property<string>("Passport")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("passport");

                    b.Property<bool>("Registration")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("registration");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("seat_number");

                    b.Property<string>("TicketNumber")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ticket_number");

                    b.HasKey("IdPassenger");

                    b.ToTable("passengers");
                });

            modelBuilder.Entity("AirlineCompany.Domain.Models.Plane", b =>
                {
                    b.Property<int>("IdPlane")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_plane");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPlane"));

                    b.Property<double>("Efficiency")
                        .HasColumnType("double")
                        .HasColumnName("efficiency");

                    b.Property<double>("LoadCapacity")
                        .HasColumnType("double")
                        .HasColumnName("load_capacity");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("model");

                    b.Property<int>("PassengerMax")
                        .HasColumnType("int")
                        .HasColumnName("passenger_max");

                    b.HasKey("IdPlane");

                    b.ToTable("planes");
                });

            modelBuilder.Entity("AirlineCompany.Domain.Models.AirFlight", b =>
                {
                    b.HasOne("AirlineCompany.Domain.Models.Plane", "Plane")
                        .WithMany()
                        .HasForeignKey("id_plane")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plane");
                });
#pragma warning restore 612, 618
        }
    }
}
